---
name: quran_hadith
description: Qur'an & Hadith
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  intl: ^0.17.0
  font_awesome_flutter: ^9.1.0
  bubble_tab_indicator: ^0.1.6
  shimmer: ^2.0.0
  shared_preferences: ^2.0.7
  auto_size_text: ^3.0.0-nullsafety.0
  url_launcher: ^6.0.9
  lottie: ^1.1.0
  provider: ^6.0.0
  get: ^4.3.8
  adaptive_breakpoints: ^0.1.0
  audioplayers: ^0.19.1
  package_info: ^2.0.2
  flutter_animated_dialog: ^2.0.1
  scroll_to_index: ^2.0.0
  animations: ^2.0.1
  popover: ^0.2.6+2
  anim_search_bar: ^2.0.2
  animated_theme_switcher: ^2.0.1
  get_storage:
  platform_device_id:
  process_run:
  just_audio: ^0.9.13
  audio_video_progress_bar: ^0.9.0
  rxdart: ^0.27.2
  coachmaker: ^0.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
    - family: Philosopher
      fonts:
        - asset: assets/fonts/Philosopher-Bold.ttf
        - asset: assets/fonts/Philosopher-Regular.ttf
        - asset: assets/fonts/Philosopher-Italic.ttf
    - family: Quattrocento
      fonts:
        - asset: assets/fonts/Quattrocento-Regular.ttf
        - asset: assets/fonts/Quattrocento-Bold.ttf
