---
name: quran_hadith
description: Qur'an & Hadith
publish_to: none
repository: https://github.com/kherld-hussein/quran_hadith
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  http:
  intl:
  font_awesome_flutter:
  bubble_tab_indicator:
  shimmer:
  shared_preferences:
  auto_size_text:
  lottie:
  provider:
  get:
  adaptive_breakpoints:
#  audioplayers: ^0.19.1
  package_info:
  flutter_animated_dialog:
  scroll_to_index:
  animations:
  popover:
  anim_search_bar:
  animated_theme_switcher:
  get_storage:
  platform_device_id:
  process_run:
  just_audio:
  audio_video_progress_bar:
  rxdart:
  coachmaker:
  desktop_notifications:
  dropdown_button2:
  url_launcher: ^6.0.20
  dio: ^4.0.4
  dio_http_cache: ^0.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
    - family: Quattrocento
      fonts:
        - asset: assets/fonts/Quattrocento-Regular.ttf
        - asset: assets/fonts/Quattrocento-Bold.ttf
    - family: Ageo
      fonts:
        - asset: assets/fonts/Ageo-Regular.ttf
        - asset: assets/fonts/Ageo-Bold.ttf
