name: quran-hadith
version: 0.1.0
summary: Qur’ān Hadith
description: Qur’ān Hadith is an Online Quran and Hadith application with fashion interface,
  smooth performance and more features to sharpens your focus on what you are reading or listening.

confinement: strict
base: core18
grade: stable # must be 'stable' to release into candidate/stable channels

slots:
  dbus-quran-hadith:
    interface: dbus
    bus: session
    name: com.kherld.quran_hadith

apps:
  quran-hadith:
    command: quran_hadith
    extensions: [ flutter-stable ] # Where "stable" defines which Flutter channel to use for the build
    slots:
      - dbus-quran-hadith
    plugs:
      - network

parts:
  quran-hadith:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
