name: quran-hadith # you probably want to 'snapcraft register <name>'
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Qur’ān Hadith
description: Qur’ān Hadith is an Online Quran and Hadith application with fashion interface,
  smooth performance and more features to sharpens your focus on what you are reading or listening.

confinement: strict
base: core18
grade: stable # must be 'stable' to release into candidate/stable channels

slots:
  dbus-quran-hadith:
    interface: dbus
    bus: session
    name: com.kherld.quran_hadith

apps:
  quran-hadith:
    command: quran_hadith
    extensions: [flutter-stable] # Where "stable" defines which Flutter channel to use for the build
    plugs:
      - network

parts:
  quran-hadith:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
